# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - readme.md
    - ShoppingList.Function/*
    - Pipelines/azure-function.yml

variables:
 # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '4a054209-2e8e-4e48-87b6-21268755f5bc'
# Agent VM image name
  vmImageName: 'vs2017-win2016'
  buildConfiguration: 'Release'

  # Working Directory
  workingDirectory: '$(Build.Repository.LocalPath)/ShoppingList.Web'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreInstaller@1
      displayName: 'Installing .NET Core SDK...'
      inputs:
        version:  3.1.100
        
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'jhueppauff-github'
        scannerMode: 'MSBuild'
        projectKey: 'shoppinglist'
        projectName: 'ShoppingList'
        extraProperties: '/o:jhueppauff-github'
    - task: DotNetCoreCli@2
      displayName: restore
      inputs:
        command: 'restore'
        projects: |
          $(workingDirectory)/*.csproj

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: |
          $(workingDirectory)/*.csproj
        arguments: --configuration $(buildConfiguration)

    - task: WhiteSource Bolt@20
    
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True


    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'drop'